name: Build Image

on:
  push:
    branches: [ master ]
    paths:
      - 'build-image/**'
      - '.github/workflows/build-image.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'build-image/**'
      - '.github/workflows/build-image.yml'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: Checkout
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5927c834f5b4fdf503fca6f4c7eccda82949e1ee # v3.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: Save image
        run: make save-multiarch-build-image

      - name: Upload Docker Images Artifacts
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: build-image
          path: |
            ./build-image-amd64.tar
            ./build-image-arm64.tar
          if-no-files-found: error

  push:
    needs: build
    if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) && github.repository == 'cortexproject/cortex'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        name: Checkout
        with:
          fetch-depth: 0

      - name: Download Docker Images Artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: build-image

      - name: Load image
        run: make load-multiarch-build-image

      - name: Login to Quay.io
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: quay.io
          username: ${{secrets.QUAY_REGISTRY_USER}}
          password: ${{secrets.QUAY_REGISTRY_PASSWORD}}

      - name: Push image
        run: make push-multiarch-build-image
